# Added to /etc/samba/smb.conf file

[NAS]
   path = /srv/nas
   browseable = yes
   writable  = yes
   read only = no

   valid users = @nasuser
   force group = nasuser

   create mask = 0664
   directory mask = 0775
   unix extensions = no

